# Generated by Django 3.0.5 on 2020-05-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libro_nombrelibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='email_solicitante',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_solicitante',
            field=models.CharField(default='', max_length=50),
        ),
    ]
