# Generated by Django 3.0.5 on 2020-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200504_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tipo_despacho',
            field=models.CharField(default='', max_length=50),
        ),
    ]
