# Generated by Django 3.0.5 on 2020-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_libro_tipo_despacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreclientes', models.CharField(default='', max_length=50)),
                ('emailclientes', models.CharField(default='', max_length=50)),
                ('celularcliente', models.IntegerField()),
                ('librocliente', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
