# Generated by Django 3.0.5 on 2020-06-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido2',
            name='tipo_pago',
            field=models.CharField(default='', max_length=50),
        ),
    ]
