# Generated by Django 3.0.5 on 2020-06-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido2_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tipo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=50)),
                ('autores', models.CharField(max_length=50)),
                ('numeropaginas', models.IntegerField()),
                ('anios', models.IntegerField()),
                ('tipo_despachos', models.CharField(default='', max_length=50)),
                ('generos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero')),
            ],
        ),
    ]
