# Generated by Django 3.0.5 on 2020-07-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido2',
            name='rut_cliente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
